basic:
  total_num: 3 #10 #20  # Total results to get, use only multiples of 'num' param
api_specific:
  cx: ''
  lr: 'lang_el'
  num: 3 #10  # max 10 results can be obtained in 1 query/page
standard_query:
  api_key: ''